# Generated by Django 3.2 on 2024-02-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverify',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
