# Generated by Django 3.2 on 2024-02-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
