# Generated by Django 6.0.1 on 2026-02-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_created_at_userprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverify',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
