# Generated by Django 3.2 on 2024-01-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='percent',
            field=models.IntegerField(null=True),
        ),
    ]
