# Generated by Django 3.2 on 2024-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_couponcode_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='coupon_agent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='coupon_agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='coupon_agent_mobile',
            field=models.CharField(default='9267678888', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='coupon_agent_name',
            field=models.CharField(default='admin', max_length=100, null=True),
        ),
    ]
