# Generated by Django 5.0.6 on 2025-01-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20240206_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
