# Generated by Django 4.0 on 2023-06-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.CharField(default=0, max_length=10)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(upload_to='course_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('attr1', models.CharField(max_length=100, null=True)),
                ('attr2', models.CharField(max_length=100, null=True)),
                ('attr3', models.CharField(max_length=100, null=True)),
                ('attr4', models.IntegerField(null=True)),
                ('attr5', models.IntegerField(null=True)),
                ('attr6', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('video_file', models.FileField(null=True, upload_to='video_file')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('attr1', models.CharField(max_length=100, null=True)),
                ('attr2', models.CharField(max_length=100, null=True)),
                ('attr3', models.CharField(max_length=100, null=True)),
                ('attr4', models.IntegerField(null=True)),
                ('attr5', models.IntegerField(null=True)),
                ('attr6', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatch_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='incomplete', max_length=25)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
                ('videofile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.videofiles')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount', models.CharField(default=0, max_length=10, null=True)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('razorpay_payment_id', models.CharField(max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(max_length=100, null=True)),
                ('razorpay_signature', models.CharField(max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('attr1', models.CharField(max_length=100, null=True)),
                ('attr2', models.CharField(max_length=100, null=True)),
                ('attr3', models.CharField(max_length=100, null=True)),
                ('attr4', models.IntegerField(null=True)),
                ('attr5', models.IntegerField(null=True)),
                ('attr6', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='AudioInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='AudioFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('audio_file', models.FileField(null=True, upload_to='audio_file')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('attr1', models.CharField(max_length=100, null=True)),
                ('attr2', models.CharField(max_length=100, null=True)),
                ('attr3', models.CharField(max_length=100, null=True)),
                ('attr4', models.IntegerField(null=True)),
                ('attr5', models.IntegerField(null=True)),
                ('attr6', models.IntegerField(null=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
            ],
        ),
    ]
