# Generated by Django 3.2 on 2024-01-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='code_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videofiles',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
