# Generated by Django 4.0 on 2023-06-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_lang',
            field=models.CharField(default='Hindi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='validate_for',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='videofiles',
            name='thumb_video',
            field=models.ImageField(default='', upload_to='thumb_image'),
        ),
    ]
