# Generated by Django 4.0 on 2023-08-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_filetype_remove_course_image_remove_videofiles_attr1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioInstructions',
        ),
    ]
