# Generated by Django 4.0 on 2023-08-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_audioinstructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_lang',
            field=models.CharField(blank=True, default='Hindi', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='demo_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='course_demo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, default='common', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='validate_for',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
