# Generated by Django 3.2 on 2024-01-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchased',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
