# Generated by Django 4.0 on 2023-06-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_image_course_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='common', max_length=50, null=True),
        ),
    ]
