# Generated by Django 3.2 on 2024-02-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursepurchased_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchased',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
