# Generated by Django 4.0 on 2023-07-14 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chunked_upload', '0002_alter_chunkedupload_id'),
        ('courses', '0005_remove_videofiles_course_delete_userwatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('chunkedupload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chunked_upload.chunkedupload')),
                ('day', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
            ],
            options={
                'abstract': False,
            },
            bases=('chunked_upload.chunkedupload',),
        ),
        migrations.CreateModel(
            name='UserWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatch_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='incomplete', max_length=25)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
                ('videofile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.videofiles')),
            ],
        ),
    ]
