# Generated by Django 4.0 on 2023-08-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_attr1_alter_course_attr2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='file',
            field=models.FileField(default='', upload_to='course_files'),
        ),
    ]
