# Generated by Django 5.0.6 on 2024-05-18 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_screencolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemaster',
            name='ScreenColumn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.screencolumn'),
        ),
    ]
