# Generated by Django 5.0.6 on 2024-08-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursemaster_screencolumn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepurchased',
            old_name='payment_status',
            new_name='delivery_status',
        ),
    ]
