# Generated by Django 5.0.6 on 2024-08-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_payment_status_coursepurchased_delivery_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepurchased',
            old_name='delivery_status',
            new_name='payment_status',
        ),
    ]
