# Generated by Django 5.0.6 on 2024-12-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursemaster_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchased',
            name='mail_delivered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
