# Generated by Django 5.0.6 on 2025-07-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursepurchased_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coupon_image',
            field=models.ImageField(blank=True, null=True, upload_to='coupon_images/'),
        ),
    ]
