# Generated by Django 5.0.6 on 2025-09-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_coupon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchased',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
