# Generated by Django 5.0.6 on 2025-09-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursepurchased_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchased',
            name='merchant_reference_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
