# Generated by Django 3.2 on 2024-03-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_coursepurchased_coupon_code'),
        ('demo', '0002_auto_20240325_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('demo_file', models.FileField(default='', upload_to='demo_class_files')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('file_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.filetype')),
            ],
        ),
    ]
