# Generated by Django 3.2 on 2024-03-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_adduserdemocode_mainuserdemo_uploaddemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuserdemo',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.uploaddemo'),
        ),
    ]
