# Generated by Django 5.0.6 on 2025-11-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20240326_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddemo',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
